admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /panel

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /panel

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
  path: /
  defaults: {_controller: EduBoxBundle:Main:home}
