admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /panel

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /panel

edubox:
  resource: '@EduBoxBundle/Controller/'
  type: annotation

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: "panel/profile"
