edu_box:
  resource: "@EduBoxBundle/Controller/"
  type:     annotation
  prefix:   /

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /panel

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /panel
