sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
  title: 'EduBox'
  options:
    title_mode: 'single_text'
  show_mosaic_button: false
  templates:
    dashboard: '@EduBox/standard_layout.html.twig'
  dashboard:
    blocks: