sonata_admin:
  security:
    handler: sonata.admin.security.handler.role
  title: 'EduBox'
  options:
    title_mode: 'single_text'
  show_mosaic_button: false
  templates:
    dashboard: '@EduBox/Admin/dashboard_admin.html.twig'
    user_block: '@EduBox/Block/user_block.html.twig'
  dashboard:
    blocks:
  assets:
    extra_javascripts:
      - 'assets/js/main.js'