services:

  edubox.admin.organisation:
    class: EduBoxBundle\Admin\OrganisationAdmin
    arguments: [~, ~, EduBoxBundle:Admin\OrganisationCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Organisation'
        label: 'Organisation'
        icon: '<i class="fa fa-graduation-cap"></i>'
        on_top: true

  edubox.admin.user:
    class: EduBoxBundle\Admin\UserAdmin
    arguments: [~, EduBoxBundle:User, EduBoxBundle:Admin\UserCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Users'
        label: 'Users'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox.admin.calendar:
    class: EduBoxBundle\Admin\CalendarAdmin
    arguments: [~, EduBoxBundle\Entity\Calendar, EduBoxBundle:Admin\CalendarCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Calendars'
        label: 'Calendars'
        icon: '<i class="fa fa-calendar"></i>'
        on_top: true

  edubox.admin.holiday:
    class: EduBoxBundle\Admin\HolidayAdmin
    arguments: [~, EduBoxBundle\Entity\Holiday, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Holidays'
        label: 'Holidays'
        icon: '<i class="fa fa-gift"></i>'
        on_top: true

  edubox.admin.students_group:
    class: EduBoxBundle\Admin\StudentsGroupAdmin
    arguments: [~, EduBoxBundle\Entity\StudentsGroup, EduBoxBundle:Admin\StudentsGroupCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Classes'
        label: 'Classes'
        icon: '<i class="fa fa-address-book"></i>'
        on_top: true

  edubox.admin.subject:
    class: EduBoxBundle\Admin\SubjectAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Subjects'
        label: 'Subjects'
        icon: '<i class="fa fa-book"></i>'
        on_top: true

  edubox.admin.subject_area:
    class: EduBoxBundle\Admin\SubjectAreaAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectAreaCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Subject areas'
        label: 'Subject areas'
        icon: '<i class="fa fa-bookmark"></i>'
        on_top: true

  edubox.admin.subject_schedule:
    class: EduBoxBundle\Admin\SubjectScheduleAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectScheduleCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Subject schedules'
        label: 'Subject schedules'
        icon: '<i class="fa fa-list"></i>'
        on_top: true

  edubox.admin.mark:
    class: EduBoxBundle\Admin\MarkAdmin
    arguments: [~, ~, EduBoxBundle:Admin\MarkCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Marks'
        label: 'Marks'
        icon: '<i class="fa fa-bar-chart"></i>'
        on_top: true

  edubox.admin.quarter:
    class: EduBoxBundle\Admin\QuarterAdmin
    arguments: [~, ~, EduBoxBundle:Admin\Quarter]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Quarters'
        label: 'Quarters'
        icon: '<i class="fa fa-bar-chart"></i>'
        on_top: true

  edubox.admin.lesson:
    class: EduBoxBundle\Admin\LessonAdmin
    arguments: [~, EduBoxBundle\Entity\Lesson, EduBoxBundle:Admin\LessonCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Lessons'
        label: 'Lessons'
        icon: '<i class="fa fa-list"></i>'
        on_top: true

  edubox.admin.homework:
    class: EduBoxBundle\Admin\HomeworkAdmin
    arguments: [~, EduBoxBundle\Entity\Homework, EduBoxBundle:Admin\HomeworkCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Homework'
        label: 'Homework'
        icon: '<i class="fa fa-home"></i>'
        on_top: true