services:

  edubox.admin.dashboard_admin:
    class: EduBoxBundle\Admin\DashboardAdminAdmin
    arguments: [~, ~, EduBoxBundle:Admin/Default]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Admin'
        label: 'Admin'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox.admin.dashboard_teacher:
    class: EduBoxBundle\Admin\DashboardTeacherAdmin
    arguments: [~, ~, EduBoxBundle:Teacher/Default]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Teacher'
        label: 'Teacher'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox.admin.dashboard_student:
    class: EduBoxBundle\Admin\DashboardStudentAdmin
    arguments: [~, ~, EduBoxBundle:Student/Default]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Student'
        label: 'Student'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox.admin.dashboard_parent:
    class: EduBoxBundle\Admin\DashboardParentAdmin
    arguments: [~, ~, EduBoxBundle:Parent/Default]
    tags:
      - name: sonata.admin
        manager_type: orm
        group: 'Parent'
        label: 'Parent'
        icon: '<i class="fa fa-users"></i>'
        on_top: true
