services:

  edubox.admin.organisation:
    class: EduBoxBundle\Admin\OrganisationAdmin
    arguments: [~, ~, EduBoxBundle:Admin\OrganisationCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'organisation'
        label: 'organisation'
        icon: '<i class="fa fa-graduation-cap"></i>'
        on_top: true

  edubox.admin.calendar:
    class: EduBoxBundle\Admin\CalendarAdmin
    arguments: [~, EduBoxBundle\Entity\Calendar, EduBoxBundle:Admin\CalendarCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'calendars'
        label: 'calendars'
        icon: '<i class="fa fa-calendar"></i>'
        on_top: true

  edubox.admin.holiday:
    class: EduBoxBundle\Admin\HolidayAdmin
    arguments: [~, EduBoxBundle\Entity\Holiday, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'holidays'
        label: 'holidays'
        icon: '<i class="fa fa-gift"></i>'
        on_top: true

  edubox.admin.subject_schedule:
    class: EduBoxBundle\Admin\SubjectScheduleAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectScheduleCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'subject_schedules'
        label: 'subject_schedules'
        icon: '<i class="fa fa-list"></i>'
        on_top: true

  edubox.admin.subject_area:
    class: EduBoxBundle\Admin\SubjectAreaAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectAreaCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'subject_areas'
        label: 'subject_areas'
        icon: '<i class="fa fa-bookmark"></i>'
        on_top: true

  edubox.admin.subject:
    class: EduBoxBundle\Admin\SubjectAdmin
    arguments: [~, ~, EduBoxBundle:Admin\SubjectCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'subjects'
        label: 'subjects'
        icon: '<i class="fa fa-book"></i>'
        on_top: true

  edubox.admin.user:
    class: EduBoxBundle\Admin\UserAdmin
    arguments: [~, EduBoxBundle:User, EduBoxBundle:Admin\UserCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'users'
        label: 'users'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox.admin.students_group:
    class: EduBoxBundle\Admin\StudentsGroupAdmin
    arguments: [~, EduBoxBundle\Entity\StudentsGroup, EduBoxBundle:Admin\StudentsGroupCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'students_groups'
        label: 'students_groups'
        icon: '<i class="fa fa-address-book"></i>'
        on_top: true

  edubox.admin.journal:
    class: EduBoxBundle\Admin\JournalAdmin
    arguments: [~, ~, EduBoxBundle:Admin\JournalCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'journal'
        label: 'journal'
        icon: '<i class="fa fa-bar-chart"></i>'
        on_top: true

  edubox.admin.diary:
    class: EduBoxBundle\Admin\DiaryAdmin
    arguments: [~, ~, EduBoxBundle:Admin\DiaryCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'diary'
        label: 'diary'
        icon: '<i class="fa fa-bar-chart"></i>'
        on_top: true

  edubox.admin.lesson:
    class: EduBoxBundle\Admin\LessonAdmin
    arguments: [~, EduBoxBundle\Entity\Lesson, EduBoxBundle:Admin\LessonCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'lessons'
        label: 'lessons'
        icon: '<i class="fa fa-list"></i>'
        on_top: true

  edubox.admin.homework:
    class: EduBoxBundle\Admin\HomeworkAdmin
    arguments: [~, EduBoxBundle\Entity\Homework, EduBoxBundle:Admin\HomeworkCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'homework'
        label: 'homework'
        icon: '<i class="fa fa-home"></i>'
        on_top: true

  edubox.admin.statistic:
    class: EduBoxBundle\Admin\StatisticAdmin
    arguments: [~, ~, EduBoxBundle:Admin\StatisticCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'statistics'
        label: 'statistics'
        icon: '<i class="fa fa-line-chart"></i>'
        on_top: true

  edubox.admin.quarter:
    class: EduBoxBundle\Admin\QuarterAdmin
    arguments: [~, ~, EduBoxBundle:Admin\Quarter]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'quarters'
        label: 'quarters'
        icon: '<i class="fa fa-bar-chart"></i>'
        on_top: true

  edubox.admin.student_rating:
    class: EduBoxBundle\Admin\StudentRatingAdmin
    arguments: [~, ~, EduBoxBundle:Admin\StudentRatingCRUD]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        group: 'rating'
        label: 'rating'
        icon: '<i class="fa fa-rocket"></i>'
        on_top: true



